---
version: '3'

services:
  boilr:
    container_name: boilr
    build: .
    volumes:
      - ./config.yaml:/config.yaml
    restart: unless-stopped
    privileged: true
    networks:
      - boilr-network

networks:
  boilr-network:
    driver: bridge
