---
version: '3'

services:
  boilr:
    container_name: boilr
    build: .
    restart: unless-stopped
    privileged: true
    #environment:
    #  - BOILR_CONFIG_PATH=/etc/boilr/config.yaml # set custom configuration path
    volumes:
      - ./config.yaml:/etc/boilr/config.yaml
    devices:
      - /dev/gpiomem:/dev/gpiomem
    networks:
      - boilr-network

networks:
  boilr-network:
    driver: bridge
